title: Shiyang JIANG
author: Shiyang Jiang
email: sygjiang@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Homepage for Shiyang Jiang

baseurl: "" # the subpath of your site, e.g. /blog
domain: digitalshiyang.github.io
url: "https://digitalshiyang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: digitalshiyang
instagram_username:
twitter_username:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
